workspace(name = "highway")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/609281088cfefc76f9d0ce82e1ff6c30cc3591e5.zip"],
  sha256 = "5cf189eb6847b4f8fc603a3ffff3b0771c08eec7dd4bd961bfd45477dd13eb73",
  strip_prefix = "googletest-609281088cfefc76f9d0ce82e1ff6c30cc3591e5",
)

# See https://google.github.io/googletest/quickstart-bazel.html
http_archive(
  name = "rules_cc",
  urls = ["https://github.com/bazelbuild/rules_cc/archive/40548a2974f1aea06215272d9c2b47a14a24e556.zip"],
  sha256 = "56ac9633c13d74cb71e0546f103ce1c58810e4a76aa8325da593ca4277908d72",
  strip_prefix = "rules_cc-40548a2974f1aea06215272d9c2b47a14a24e556",
)

# Need recent version for config_setting_group
http_archive(
    name = "bazel_skylib",
    urls = ["https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz"],
)

new_local_repository(
  name = "ips4o",
  path = "../ips4o/",
  build_file_content = """
package(default_visibility = ["//visibility:public"])
cc_library(
  name = "ips4o",
  hdrs = ["include/ips4o.hpp"],
  srcs = glob(["include/**/*.hpp"]),
  defines = ["_REENTRANT"],
  copts = [
    "-mcx16", 
    "-march=native"
  ]
)
"""
)